# Generated by Django 3.1.5 on 2021-03-24 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definitive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_battles', to='definitive.rankitem')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_battles', to='definitive.rankitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='definitive.rankitem')),
            ],
        ),
    ]
