# Generated by Django 3.1.5 on 2021-04-08 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitive', '0003_auto_20210330_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranklist',
            name='open_until',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
